/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo2;
import java.sql.*;
import java.util.*;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());


        // Load database driver in memory
        Scanner sc=new Scanner(System.in);
        System.out.println("Enter Id"); 
        int id=sc.nextInt();
   
        System.out.println("Enter Name"); 
        String name=sc.next();
       
        Class.forName("org.postgresql.Driver");
        System.out.println("Driver loaded");
        Connection conn;
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/test", "postgres", "root");

        System.out.println("Coonection done");

        Statement stmt;
        stmt=conn.createStatement();
        String sql;
        sql="insert into student values("+id+",'"+name+"')";
        stmt.executeUpdate(sql);
        System.out.println("record inserted");
        sc.close();

        conn.close();
    }
}
